# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'film_recommend.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(527, 460)
        Form.setWindowTitle('电影推荐系统')
        Form.setWindowIcon(QtGui.QIcon('./images/tvtv.jpg'))
        window_pale = QtGui.QPalette()
        window_pale.setBrush(Form.backgroundRole(),
                             QtGui.QBrush(QtGui.QPixmap("./images/bgbg.jpg")))
        Form.setPalette(window_pale)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 50, 161, 31))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(70, 90, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 161, 31))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 160, 141, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 190, 161, 31))
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(70, 230, 211, 131))
        self.textEdit.setObjectName("textEdit")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 390, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 390, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 390, 75, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox.addItem("")
        self.comboBox.currentText()
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.acheieveData)
        self.pushButton_2.clicked.connect(Form.searchData)
        self.pushButton_3.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "电影推荐系统"))
        self.label.setText(_translate("Form", "请选择想看的电影类型"))
        self.label_2.setText(_translate("Form", "您想观看哪国的影视作品"))
        self.label_3.setText(_translate("Form", "特为您推荐以下作品："))
        self.pushButton.setText(_translate("Form", "获取数据"))
        self.pushButton_2.setText(_translate("Form", "数据检索"))
        self.pushButton_3.setText(_translate("Form", "退出程序"))
        self.comboBox.setItemText(0, _translate("Form", "犯罪"))
        self.comboBox.setItemText(1, _translate("Form", "剧情"))
        self.comboBox.setItemText(2, _translate("Form", "爱情"))
        self.comboBox.setItemText(3, _translate("Form", "动作"))
        self.comboBox.setItemText(4, _translate("Form", "战争"))
        self.comboBox.setItemText(5, _translate("Form", "灾难"))
        self.comboBox.setItemText(6, _translate("Form", "动画"))
        self.comboBox.setItemText(7, _translate("Form", "奇幻"))
        self.comboBox.setItemText(8, _translate("Form", "历史"))
        self.comboBox.setItemText(9, _translate("Form", "悬疑"))
        self.comboBox.setItemText(10, _translate("Form", "冒险"))
        self.comboBox.setItemText(11, _translate("Form", "科幻"))
        self.comboBox.setItemText(12, _translate("Form", "音乐"))
        self.comboBox.setItemText(13, _translate("Form", "喜剧"))
        self.comboBox.setItemText(14, _translate("Form", "惊悚"))
        self.comboBox.setItemText(15, _translate("Form", "传记"))
        self.comboBox_2.setItemText(0, _translate("Form", "美国"))
        self.comboBox_2.setItemText(1, _translate("Form", "中国"))
        self.comboBox_2.setItemText(2, _translate("Form", "法国"))
        self.comboBox_2.setItemText(3, _translate("Form", "意大利"))
        self.comboBox_2.setItemText(4, _translate("Form", "日本"))
        self.comboBox_2.setItemText(5, _translate("Form", "英国"))
        self.comboBox_2.setItemText(6, _translate("Form", "印度"))
        self.comboBox_2.setItemText(7, _translate("Form", "韩国"))
        self.comboBox_2.setItemText(8, _translate("Form", "瑞士"))
        self.comboBox_2.setItemText(9, _translate("Form", "德国"))
        self.comboBox_2.setItemText(10, _translate("Form", "西班牙"))


