# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageProcess.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1112, 899)
        Form.setWindowTitle('图像处理软件')
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(480, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(60, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(63, 150, 1000, 600))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 640, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 640, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 640, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(570, 640, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(740, 640, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 740, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(230, 740, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(400, 740, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(570, 740, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(740, 740, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(910, 640, 181, 31))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(910, 680, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(910, 740, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton.clicked.connect(Form.loading)
        self.pushButton_2.clicked.connect(Form.jiazai)
        self.pushButton_4.clicked.connect(Form.form_icon)
        self.pushButton_3.clicked.connect(Form.hand_writing)
        self.pushButton_5.clicked.connect(Form.fudiao)
        self.pushButton_6.clicked.connect(Form.lvjing)
        self.pushButton_7.clicked.connect(Form.duibidu)
        self.pushButton_8.clicked.connect(Form.balance)
        self.pushButton_9.clicked.connect(Form.brightness)
        self.pushButton_10.clicked.connect(Form.sharpness)
        self.pushButton_11.clicked.connect(Form.pic_save)
        self.pushButton_12.clicked.connect(Form.pic_trans)

        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图像处理软件"))
        self.label.setText(_translate("Form", "图像处理软件"))
        self.pushButton.setText(_translate("Form", "读取路径"))
        self.label_2.setText(_translate("Form", " "))
        self.pushButton_2.setText(_translate("Form", "加载图片"))
        self.pushButton_3.setText(_translate("Form", "手绘效果"))
        self.pushButton_4.setText(_translate("Form", "形成图标"))
        self.pushButton_5.setText(_translate("Form", "浮雕效果"))
        self.pushButton_6.setText(_translate("Form", "灰白滤镜"))
        self.pushButton_7.setText(_translate("Form", "增强对比度"))
        self.pushButton_8.setText(_translate("Form", "颜色平衡"))
        self.pushButton_9.setText(_translate("Form", "增加亮度"))
        self.pushButton_10.setText(_translate("Form", "增加锐度"))
        self.pushButton_11.setText(_translate("Form", "存储图片"))
        self.label_3.setText(_translate("Form", "请选择你要生成的图片格式"))
        self.pushButton_12.setText(_translate("Form", "格式转换"))
        self.comboBox.setItemText(0, _translate("Form", ".jpg"))
        self.comboBox.setItemText(1, _translate("Form", ".png"))
        self.comboBox.setItemText(2, _translate("Form", ".gif"))
        self.comboBox.setItemText(3, _translate("Form", ".pdf"))