# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WeatherWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 347)
        Form.setWindowTitle('天气查询软件')
        Form.setWindowIcon(QtGui.QIcon('./images/yunicon.jpg'))
        window_pale = QtGui.QPalette()
        window_pale.setBrush(Form.backgroundRole(),
                             QtGui.QBrush(QtGui.QPixmap("./images/bgbg.jpg")))
        Form.setPalette(window_pale)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 251))
        self.groupBox.setObjectName("groupBox")
        self.weatherComboBox = QtWidgets.QComboBox(self.groupBox)
        self.weatherComboBox.setGeometry(QtCore.QRect(60, 30, 131, 21))
        self.weatherComboBox.setObjectName("weatherComboBox")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")

        self.resultText = QtWidgets.QTextEdit(self.groupBox)
        self.resultText.setGeometry(QtCore.QRect(10, 60, 411, 181))
        self.resultText.setObjectName("resultText")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 72, 21))
        self.label.setObjectName("label")
        self.queryBtn = QtWidgets.QPushButton(Form)
        self.queryBtn.setGeometry(QtCore.QRect(90, 300, 93, 28))
        self.queryBtn.setObjectName("queryBtn")
        self.clearBtn = QtWidgets.QPushButton(Form)
        self.clearBtn.setGeometry(QtCore.QRect(230, 300, 93, 28))
        self.clearBtn.setObjectName("clearBtn")

        self.retranslateUi(Form)
        self.clearBtn.clicked.connect(Form.clearResult)
        self.queryBtn.clicked.connect(Form.queryWeather)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "天气查询系统"))
        self.groupBox.setTitle(_translate("Form", "查询城市天气"))
        self.weatherComboBox.setItemText(0, _translate("Form", "北京"))
        self.weatherComboBox.setItemText(1, _translate("Form", "天津"))
        self.weatherComboBox.setItemText(2, _translate("Form", "上海"))
        self.weatherComboBox.setItemText(3, _translate("Form", "重庆"))
        self.weatherComboBox.setItemText(4, _translate("Form", "南京"))
        self.weatherComboBox.setItemText(5, _translate("Form", "苏州"))
        self.weatherComboBox.setItemText(6, _translate("Form", "泰州"))
        self.weatherComboBox.setItemText(7, _translate("Form", "无锡"))
        self.weatherComboBox.setItemText(8, _translate("Form", "镇江"))
        self.weatherComboBox.setItemText(9, _translate("Form", "南通"))
        self.weatherComboBox.setItemText(10, _translate("Form", "盐城"))
        self.weatherComboBox.setItemText(11, _translate("Form", "徐州"))
        self.weatherComboBox.setItemText(12, _translate("Form", "淮安"))
        self.weatherComboBox.setItemText(13, _translate("Form", "常州"))
        self.weatherComboBox.setItemText(14, _translate("Form", "哈尔滨"))
        self.weatherComboBox.setItemText(15, _translate("Form", "齐齐哈尔"))
        self.weatherComboBox.setItemText(16, _translate("Form", "大兴安岭"))
        self.weatherComboBox.setItemText(17, _translate("Form", "长春"))
        self.weatherComboBox.setItemText(18, _translate("Form", "吉林"))
        self.weatherComboBox.setItemText(19, _translate("Form", "通化"))
        self.weatherComboBox.setItemText(20, _translate("Form", "沈阳"))
        self.weatherComboBox.setItemText(21, _translate("Form", "大连"))
        self.weatherComboBox.setItemText(22, _translate("Form", "抚顺"))
        self.weatherComboBox.setItemText(23, _translate("Form", "锦州"))
        self.weatherComboBox.setItemText(24, _translate("Form", "辽阳"))
        self.weatherComboBox.setItemText(25, _translate("Form", "铁岭"))
        self.weatherComboBox.setItemText(26, _translate("Form", "呼和浩特"))
        self.weatherComboBox.setItemText(27, _translate("Form", "石家庄"))
        self.weatherComboBox.setItemText(28, _translate("Form", "唐山"))
        self.weatherComboBox.setItemText(29, _translate("Form", "廊坊"))
        self.weatherComboBox.setItemText(30, _translate("Form", "衡水"))
        self.weatherComboBox.setItemText(31, _translate("Form", "邯郸"))
        self.weatherComboBox.setItemText(32, _translate("Form", "秦皇岛"))
        self.weatherComboBox.setItemText(33, _translate("Form", "雄安新区"))
        self.weatherComboBox.setItemText(34, _translate("Form", "太原"))
        self.weatherComboBox.setItemText(35, _translate("Form", "西安"))
        self.weatherComboBox.setItemText(36, _translate("Form", "济南"))
        self.weatherComboBox.setItemText(37, _translate("Form", "青岛"))
        self.weatherComboBox.setItemText(38, _translate("Form", "烟台"))
        self.weatherComboBox.setItemText(39, _translate("Form", "潍坊"))
        self.weatherComboBox.setItemText(40, _translate("Form", "临沂"))
        self.weatherComboBox.setItemText(41, _translate("Form", "乌鲁木齐"))
        self.weatherComboBox.setItemText(42, _translate("Form", "拉萨"))
        self.weatherComboBox.setItemText(43, _translate("Form", "西宁"))
        self.weatherComboBox.setItemText(44, _translate("Form", "兰州"))
        self.weatherComboBox.setItemText(45, _translate("Form", "酒泉"))
        self.weatherComboBox.setItemText(46, _translate("Form", "天水"))
        self.weatherComboBox.setItemText(47, _translate("Form", "银川"))
        self.weatherComboBox.setItemText(48, _translate("Form", "郑州"))
        self.weatherComboBox.setItemText(49, _translate("Form", "许昌"))
        self.weatherComboBox.setItemText(50, _translate("Form", "洛阳"))
        self.weatherComboBox.setItemText(51, _translate("Form", "武汉"))
        self.weatherComboBox.setItemText(52, _translate("Form", "杭州"))
        self.weatherComboBox.setItemText(53, _translate("Form", "合肥"))
        self.weatherComboBox.setItemText(54, _translate("Form", "福州"))
        self.weatherComboBox.setItemText(55, _translate("Form", "南昌"))
        self.weatherComboBox.setItemText(56, _translate("Form", "长沙"))
        self.weatherComboBox.setItemText(57, _translate("Form", "贵阳"))
        self.weatherComboBox.setItemText(58, _translate("Form", "成都"))
        self.weatherComboBox.setItemText(59, _translate("Form", "广州"))
        self.weatherComboBox.setItemText(60, _translate("Form", "昆明"))
        self.weatherComboBox.setItemText(61, _translate("Form", "南宁"))
        self.weatherComboBox.setItemText(62, _translate("Form", "海口"))
        self.weatherComboBox.setItemText(63, _translate("Form", "香港"))
        self.weatherComboBox.setItemText(64, _translate("Form", "澳门"))
        self.weatherComboBox.setItemText(65, _translate("Form", "台北"))
        self.label.setText(_translate("Form", "城市"))
        self.queryBtn.setText(_translate("Form", "查询"))
        self.clearBtn.setText(_translate("Form", "清空"))

